import { theme, type ThemeConfig } from 'antd'
import { clanerPalette as c, clanerRadius as r, clanerType as t } from './palette'

/**
 * Global antd theme — Minimal White (docs/10-frontend-theme.md).
 * Seed colors mirror `tokens.css` / `palette.ts`. Change palette once, both stay aligned.
 */
export const antdTheme: ThemeConfig = {
  algorithm: theme.defaultAlgorithm,
  cssVar: {
    key: 'claner',
  },
  hashed: true,
  token: {
    // —— Brand / status ——
    colorPrimary: c.accent,
    colorPrimaryHover: c.accentHover,
    colorPrimaryActive: c.ink,
    colorPrimaryBg: c.accentMist,
    colorPrimaryBgHover: c.accentSoft,
    colorPrimaryBorder: c.borderStrong,
    colorPrimaryBorderHover: c.inkSoft,
    colorPrimaryText: c.accent,
    colorPrimaryTextHover: c.accentHover,
    colorPrimaryTextActive: c.ink,

    colorInfo: c.accent,
    colorInfoBg: c.accentMist,
    colorInfoBorder: c.borderStrong,
    colorInfoText: c.ink,

    colorSuccess: c.ok,
    colorSuccessBg: c.okSoft,
    colorSuccessBorder: c.ok,
    colorSuccessText: c.ok,

    colorError: c.err,
    colorErrorBg: c.errSoft,
    colorErrorBorder: c.err,
    colorErrorText: c.err,
    colorErrorHover: '#912018',
    colorErrorActive: '#7a1810',

    colorWarning: c.warning,
    colorWarningBg: c.warningSoft,
    colorWarningBorder: c.warning,
    colorWarningText: c.warning,

    colorLink: c.ink,
    colorLinkHover: c.accentHover,
    colorLinkActive: c.ink,

    // —— Text ——
    colorText: c.ink,
    colorTextSecondary: c.muted,
    colorTextTertiary: c.faint,
    colorTextQuaternary: c.faint,
    colorTextBase: c.ink,
    colorTextHeading: c.ink,
    colorTextDescription: c.muted,
    colorTextDisabled: c.faint,
    colorTextPlaceholder: c.faint,

    // —— Background / fill ——
    colorBgBase: c.bg,
    colorBgContainer: c.surface,
    colorBgElevated: c.surface,
    colorBgLayout: c.bg,
    colorBgSpotlight: c.bgDeep,
    colorBgMask: 'rgba(17, 17, 17, 0.45)',
    colorFill: c.accentSoft,
    colorFillSecondary: c.accentMist,
    colorFillTertiary: c.bgDeep,
    colorFillQuaternary: c.bgDeep,

    // —— Border ——
    colorBorder: c.borderStrong,
    colorBorderSecondary: c.border,
    colorSplit: c.border,

    // —— Typography ——
    fontFamily: t.fontBody,
    fontFamilyCode: t.fontMono,
    fontSize: t.fontSize,
    fontSizeHeading1: 24,
    fontSizeHeading2: 20,
    fontSizeHeading3: 18,
    fontSizeHeading4: 16,
    fontSizeHeading5: 15,
    lineHeight: t.lineHeight,
    fontWeightStrong: 600,

    // —— Shape / control ——
    borderRadius: r.sm,
    borderRadiusLG: r.md,
    borderRadiusSM: 6,
    borderRadiusXS: 4,
    controlHeight: 36,
    controlHeightLG: 40,
    controlHeightSM: 28,
    controlOutlineWidth: 0,
    lineWidth: 1,
    lineWidthBold: 1,

    // —— Motion (quiet) ——
    motionDurationFast: '0.14s',
    motionDurationMid: '0.22s',
    motionDurationSlow: '0.28s',
    motionEaseOut: 'cubic-bezier(0.22, 1, 0.36, 1)',
    motionEaseInOut: 'cubic-bezier(0.22, 1, 0.36, 1)',

    // —— Shadows: cards stay flat; floating layers (Dropdown/Select) need lift ——
    boxShadow: 'none',
    boxShadowSecondary:
      '0 6px 16px rgba(17, 17, 17, 0.08), 0 3px 6px -4px rgba(17, 17, 17, 0.12)',
    boxShadowTertiary: 'none',
  },
  components: {
    Button: {
      primaryShadow: 'none',
      defaultShadow: 'none',
      dangerShadow: 'none',
      fontWeight: 500,
      borderRadius: r.sm,
      borderRadiusLG: r.sm,
      borderRadiusSM: 6,
      controlHeight: 36,
      paddingInline: 16,
      defaultBorderColor: c.borderStrong,
      defaultColor: c.ink,
      defaultBg: c.surface,
      defaultHoverBg: c.bgDeep,
      defaultHoverColor: c.ink,
      defaultHoverBorderColor: c.borderStrong,
      defaultActiveBg: c.bgDeep,
      defaultActiveBorderColor: c.inkSoft,
      textHoverBg: c.accentSoft,
      linkHoverBg: 'transparent',
      colorLink: c.muted,
      colorLinkHover: c.ink,
      colorPrimary: c.accent,
      colorPrimaryHover: c.accentHover,
      primaryColor: c.onAccent,
      dangerColor: c.err,
    },
    Input: {
      activeShadow: 'none',
      errorActiveShadow: 'none',
      warningActiveShadow: 'none',
      hoverBorderColor: c.ink,
      activeBorderColor: c.ink,
      colorBgContainer: c.surface,
      paddingBlock: 8,
      paddingInline: 12,
      borderRadius: r.sm,
      inputFontSize: t.fontSize,
    },
    InputNumber: {
      activeShadow: 'none',
      hoverBorderColor: c.ink,
      activeBorderColor: c.ink,
    },
    Select: {
      optionSelectedBg: c.accentSoft,
      optionActiveBg: c.bgDeep,
      optionSelectedColor: c.ink,
      colorBgContainer: c.surface,
      borderRadius: r.sm,
      controlOutline: 'transparent',
    },
    Cascader: {
      optionSelectedBg: c.accentSoft,
    },
    DatePicker: {
      activeShadow: 'none',
      cellActiveWithRangeBg: c.accentSoft,
      cellHoverBg: c.bgDeep,
    },
    Checkbox: {
      borderRadiusSM: 4,
      colorPrimary: c.accent,
      colorBgContainer: c.surface,
    },
    Radio: {
      colorPrimary: c.accent,
      buttonCheckedBg: c.accent,
      buttonSolidCheckedColor: c.onAccent,
    },
    Switch: {
      colorPrimary: c.accent,
      colorPrimaryHover: c.accentHover,
    },
    Form: {
      labelColor: c.ink,
      labelFontSize: t.fontSize,
      itemMarginBottom: 16,
      verticalLabelPadding: '0 0 6px',
    },
    Upload: {
      colorFillAlter: c.bgDeep,
      colorBorder: c.borderStrong,
      actionsColor: c.muted,
      borderRadiusLG: r.sm,
    },
    Modal: {
      contentBg: c.surface,
      headerBg: c.surface,
      footerBg: c.surface,
      titleColor: c.ink,
      titleFontSize: 16,
      borderRadiusLG: r.md,
      boxShadow: 'none',
    },
    Drawer: {
      colorBgElevated: c.surface,
      footerPaddingBlock: 12,
      footerPaddingInline: 16,
    },
    Dropdown: {
      borderRadiusLG: r.sm,
      paddingBlock: 4,
      colorBgElevated: c.surface,
      controlItemBgHover: c.bgDeep,
      controlItemBgActive: c.accentSoft,
    },
    Menu: {
      itemBg: 'transparent',
      itemColor: c.ink,
      itemHoverColor: c.ink,
      itemHoverBg: c.bgDeep,
      itemSelectedColor: c.ink,
      itemSelectedBg: c.accentSoft,
      itemActiveBg: c.accentSoft,
      subMenuItemBg: c.surface,
      popupBg: c.surface,
      activeBarBorderWidth: 0,
      itemBorderRadius: r.sm,
      itemMarginInline: 4,
      iconSize: 16,
    },
    Tabs: {
      itemColor: c.muted,
      itemHoverColor: c.ink,
      itemSelectedColor: c.ink,
      itemActiveColor: c.ink,
      inkBarColor: c.accent,
      titleFontSize: t.fontSize,
      horizontalItemPadding: '10px 0',
      horizontalItemGutter: 24,
      cardBg: c.bgDeep,
    },
    Table: {
      headerBg: c.bgDeep,
      headerColor: c.ink,
      headerSplitColor: c.border,
      rowHoverBg: c.bgDeep,
      borderColor: c.border,
      footerBg: c.bgDeep,
      headerBorderRadius: r.sm,
      cellPaddingBlock: 12,
      cellPaddingInline: 12,
    },
    Pagination: {
      itemActiveBg: c.accent,
      colorPrimary: c.accent,
      colorPrimaryHover: c.accentHover,
      borderRadius: r.sm,
    },
    Tag: {
      defaultBg: c.bgDeep,
      defaultColor: c.inkSoft,
      borderRadiusSM: 6,
    },
    Badge: {
      colorError: c.err,
      colorSuccess: c.ok,
      colorWarning: c.warning,
    },
    Alert: {
      borderRadiusLG: r.sm,
      withDescriptionPadding: '12px 14px',
      defaultPadding: '8px 12px',
      colorInfoBg: c.accentMist,
      colorInfoBorder: c.border,
      colorSuccessBg: c.okSoft,
      colorErrorBg: c.errSoft,
      colorWarningBg: c.warningSoft,
    },
    Message: {
      contentBg: c.surface,
      contentPadding: '10px 14px',
      borderRadiusLG: r.sm,
    },
    Notification: {
      width: 360,
      borderRadiusLG: r.md,
    },
    Tooltip: {
      colorBgSpotlight: c.ink,
      colorTextLightSolid: c.onAccent,
      borderRadius: 6,
    },
    Popover: {
      colorBgElevated: c.surface,
      borderRadiusLG: r.sm,
    },
    Card: {
      colorBgContainer: c.surface,
      colorBorderSecondary: c.border,
      borderRadiusLG: r.md,
      headerFontSize: 16,
      paddingLG: 16,
      boxShadow: 'none',
      boxShadowTertiary: 'none',
    },
    Divider: {
      colorSplit: c.border,
      orientationMargin: 0.05,
    },
    Progress: {
      defaultColor: c.accent,
      remainingColor: c.border,
      circleTextColor: c.ink,
    },
    Spin: {
      colorPrimary: c.accent,
    },
    Skeleton: {
      gradientFromColor: c.bgDeep,
      gradientToColor: c.border,
    },
    Empty: {
      colorTextDescription: c.muted,
    },
    Segmented: {
      trackBg: c.bgDeep,
      itemSelectedBg: c.surface,
      itemSelectedColor: c.ink,
      itemColor: c.muted,
      itemHoverColor: c.ink,
      borderRadius: r.sm,
      borderRadiusSM: 6,
    },
    Steps: {
      colorPrimary: c.accent,
      colorTextDescription: c.muted,
    },
    Anchor: {
      colorPrimary: c.accent,
      linkPaddingBlock: 4,
    },
    Breadcrumb: {
      itemColor: c.muted,
      lastItemColor: c.ink,
      linkColor: c.muted,
      linkHoverColor: c.ink,
      separatorColor: c.faint,
    },
  },
}
