from django.urls import path

from .views import (
    AlbumDetailView,
    AlbumItemDeleteView,
    AlbumItemListCreateView,
    AlbumListCreateView,
    CommentDeleteView,
    GrowthRecordDetailView,
    GrowthRecordListCreateView,
    KinshipDetailView,
    KinshipListCreateView,
    MediaCommentListCreateView,
    MediaCompleteView,
    MediaLibraryListView,
    MediaLocalPutView,
    MediaPresignView,
    MembershipDetailView,
    MembershipInviteView,
    MembershipListView,
    MembershipMeView,
    RecordCommentListCreateView,
    WorkspaceAvatarView,
    WorkspaceDetailView,
    WorkspaceGraphView,
    WorkspaceListView,
)

urlpatterns = [
    path("workspaces/", WorkspaceListView.as_view(), name="workspace-list"),
    path(
        "workspaces/<int:pk>/",
        WorkspaceDetailView.as_view(),
        name="workspace-detail",
    ),
    path(
        "workspaces/<int:workspace_id>/avatar/",
        WorkspaceAvatarView.as_view(),
        name="workspace-avatar",
    ),
    path(
        "workspaces/<int:workspace_id>/graph/",
        WorkspaceGraphView.as_view(),
        name="workspace-graph",
    ),
    path(
        "workspaces/<int:workspace_id>/kinship/",
        KinshipListCreateView.as_view(),
        name="workspace-kinship",
    ),
    path(
        "workspaces/<int:workspace_id>/kinship/<int:kid>/",
        KinshipDetailView.as_view(),
        name="workspace-kinship-detail",
    ),
    path(
        "workspaces/<int:workspace_id>/members/invite/",
        MembershipInviteView.as_view(),
        name="workspace-members-invite",
    ),
    path(
        "workspaces/<int:workspace_id>/members/me/",
        MembershipMeView.as_view(),
        name="workspace-members-me",
    ),
    path(
        "workspaces/<int:workspace_id>/members/",
        MembershipListView.as_view(),
        name="workspace-members",
    ),
    path(
        "workspaces/<int:workspace_id>/members/<int:mid>/",
        MembershipDetailView.as_view(),
        name="workspace-member-detail",
    ),
    path(
        "workspaces/<int:workspace_id>/records/",
        GrowthRecordListCreateView.as_view(),
        name="workspace-records",
    ),
    path(
        "workspaces/<int:workspace_id>/records/<int:rid>/comments/",
        RecordCommentListCreateView.as_view(),
        name="workspace-record-comments",
    ),
    path(
        "workspaces/<int:workspace_id>/records/<int:rid>/",
        GrowthRecordDetailView.as_view(),
        name="workspace-record-detail",
    ),
    path(
        "workspaces/<int:workspace_id>/media/presign/",
        MediaPresignView.as_view(),
        name="workspace-media-presign",
    ),
    path(
        "workspaces/<int:workspace_id>/media/complete/",
        MediaCompleteView.as_view(),
        name="workspace-media-complete",
    ),
    path(
        "workspaces/<int:workspace_id>/media/local-put/",
        MediaLocalPutView.as_view(),
        name="workspace-media-local-put",
    ),
    path(
        "workspaces/<int:workspace_id>/media/<int:mid>/comments/",
        MediaCommentListCreateView.as_view(),
        name="workspace-media-comments",
    ),
    path(
        "workspaces/<int:workspace_id>/media/",
        MediaLibraryListView.as_view(),
        name="workspace-media-list",
    ),
    path(
        "workspaces/<int:workspace_id>/albums/",
        AlbumListCreateView.as_view(),
        name="workspace-albums",
    ),
    path(
        "workspaces/<int:workspace_id>/albums/<int:album_id>/",
        AlbumDetailView.as_view(),
        name="workspace-album-detail",
    ),
    path(
        "workspaces/<int:workspace_id>/albums/<int:album_id>/items/",
        AlbumItemListCreateView.as_view(),
        name="workspace-album-items",
    ),
    path(
        "workspaces/<int:workspace_id>/albums/<int:album_id>/items/<int:media_id>/",
        AlbumItemDeleteView.as_view(),
        name="workspace-album-item-delete",
    ),
    path(
        "workspaces/<int:workspace_id>/comments/<int:cid>/",
        CommentDeleteView.as_view(),
        name="workspace-comment-delete",
    ),
]
