# Generated by Django 6.1.1 on 2026-09-15 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0002_growthrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_key', models.CharField(max_length=500, unique=True)),
                ('file_url', models.CharField(max_length=500)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], max_length=10)),
                ('thumbnail_url', models.CharField(blank=True, max_length=500)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('camera_make', models.CharField(blank=True, max_length=100)),
                ('camera_model', models.CharField(blank=True, max_length=100)),
                ('orientation', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('exif_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='clan.growthrecord')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='clan.workspace')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['record'], name='clan_mediaa_record__f182f7_idx'), models.Index(fields=['workspace'], name='clan_mediaa_workspa_56234c_idx'), models.Index(fields=['workspace', 'taken_at'], name='clan_mediaa_workspa_ba8128_idx')],
            },
        ),
    ]
