# Generated by Django 6.1.1 on 2026-09-15 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0003_mediaasset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='clan.mediaasset')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='clan.growthrecord')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='clan.workspace')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['workspace', '-created_at'], name='clan_commen_workspa_7b758b_idx'), models.Index(fields=['record', '-created_at'], name='clan_commen_record__6a6bb2_idx'), models.Index(fields=['media', '-created_at'], name='clan_commen_media_i_56ffac_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('media__isnull', True), ('record__isnull', False)), models.Q(('media__isnull', False), ('record__isnull', True)), _connector='OR'), name='comment_exactly_one_target')],
            },
        ),
    ]
