# Generated by Django 6.1.1 on 2026-09-15 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_comments', to='clan.mediaasset'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
    ]
