# Generated by Django 6.1.1 on 2026-09-28 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_to_baby_links(apps, schema_editor):
    Membership = apps.get_model("clan", "Membership")
    KinshipLink = apps.get_model("clan", "KinshipLink")
    for m in Membership.objects.all().iterator():
        if KinshipLink.objects.filter(
            from_membership_id=m.id,
            link_kind="to_baby",
        ).exists():
            continue
        KinshipLink.objects.create(
            workspace_id=m.workspace_id,
            from_membership_id=m.id,
            to_membership_id=None,
            to_baby=True,
            label=m.relation_label,
            link_kind="to_baby",
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("clan", "0005_comment_audio"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="avatar_url",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="membership",
            name="bio",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="membership",
            name="display_name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="membership",
            name="generation",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="KinshipLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("to_baby", models.BooleanField(default=False)),
                ("label", models.CharField(max_length=40)),
                (
                    "link_kind",
                    models.CharField(
                        choices=[("to_baby", "To baby"), ("peer", "Peer")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_kinship_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links_from",
                        to="clan.membership",
                    ),
                ),
                (
                    "to_membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links_to",
                        to="clan.membership",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kinship_links",
                        to="clan.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["workspace"],
                        name="clan_kinshi_workspa_8ec043_idx",
                    ),
                    models.Index(
                        fields=["workspace", "link_kind"],
                        name="clan_kinshi_workspa_0b2cd7_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("from_membership__isnull", False),
                                ("link_kind", "to_baby"),
                                ("to_baby", True),
                                ("to_membership__isnull", True),
                            ),
                            models.Q(
                                ("from_membership__isnull", False),
                                ("link_kind", "peer"),
                                ("to_baby", False),
                                ("to_membership__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="kinship_link_shape",
                    )
                ],
            },
        ),
        migrations.RunPython(backfill_to_baby_links, noop_reverse),
    ]
