# Generated by Django 6.1.1 on 2026-10-05 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0007_mediaasset_for_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AlbumItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.RenameIndex(
            model_name='mediaasset',
            new_name='clan_mediaa_record__be63f5_idx',
            old_name='clan_mediaa_record__7c0f0e_idx',
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='clan.growthrecord'),
        ),
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covering_albums', to='clan.mediaasset'),
        ),
        migrations.AddField(
            model_name='album',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_albums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='album',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='clan.workspace'),
        ),
        migrations.AddField(
            model_name='albumitem',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='album_items_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='albumitem',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clan.album'),
        ),
        migrations.AddField(
            model_name='albumitem',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_items', to='clan.mediaasset'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['workspace', '-updated_at'], name='clan_album_workspa_144d7c_idx'),
        ),
        migrations.AddIndex(
            model_name='albumitem',
            index=models.Index(fields=['album', 'sort_order', 'id'], name='clan_albumi_album_i_f34e30_idx'),
        ),
        migrations.AddConstraint(
            model_name='albumitem',
            constraint=models.UniqueConstraint(fields=('album', 'media'), name='album_item_unique_media'),
        ),
    ]
